### ISSUE TITLE
Add a list of sites that change clipboard content to the readme

### ISSUE THREAD

**Issue by Gitoffthelawn** [roedesh/copyguard#12]
I think it might be nice (and valuable) to include a list of sites people find that change the clipboard contents in the GitHub readme.

At some point, if there are enough contributions, the extension could then operate in one of 2 user-selectable modes: (1) on known sites, (2) on all sites.  Depending on your thoughts on #3, a third mode could be added: (3) on-demand.

**Comment by roedesh** [comment]
> I think it might be nice (and valuable) to include a list of sites people find that change the clipboard contents in the GitHub readme.

I was thinking earlier today to do add some kind of logging to the extension. This would:

- Allow users to see which sites altered the clipboard, how it was altered, and how many times each site altered it
- Allow the extension to send this data somewhere. No user data or clipboard contents would be sent, just addresses of websites that altered the clipboard and how many times they did it. This would be opt-in.
    - Whitelisted websites will not be considered
    - Would need to find a good way to automatically send this data, and put it back in the repo, as that seems the best place to store this data
    - If users do not opt-in, they could still manually contribute their data

> At some point, if there are enough contributions, the extension could then operate in one of 2 user-selectable modes: (1) on known sites, (2) on all sites. 

I like this idea, but we would indeed first need to get enough contributions. If a list is kept in this repo, the extension could simply load that list when the "known sites" mode is active.

**Comment by Gitoffthelawn** [comment]
Good ideas.  I have some initial thoughts on them, but let me let them simmer in my brain for a bit before I write back.

**Comment by roedesh** [comment]
Another idea that I had was that the extension could show a small warning banner on known sites:

> This website is known to alter clipboard data. Be careful!

Of course the user can disable this if they don't like it.

**Comment by Gitoffthelawn** [comment]
> Another idea that I had was that the extension could show a small warning banner on known sites:
> 
> > This website is known to alter clipboard data. Be careful!
> 
> Of course the user can disable this if they don't like it.

I really like that idea.  It could be a warning banner added to the DOM, a browser notification, a toolbar button change, or a couple other options.  I'm going to think about the possibilities.

**Comment by roedesh** [comment]
Great! Curious to hear your feedback.

In the meantime I have already implemented a new Insights page, which you can try in this branch: https://github.com/roedesh/copyguard/tree/feature/logging

**Comment by roedesh** [comment]
I just uploaded version 1.3.0 to the extension stores, which contains the feature I mentioned above. Give it a try!
