### ISSUE TITLE
Consider publishing to Chrome Webstore

### ISSUE THREAD

**Issue by kaushalyap** [roedesh/copyguard#2]

**Comment by roedesh** [comment]
Closing this as it is already published there. You can find the link in the README.

**Comment by kaushalyap** [comment]
@roedesh I do not see link in README

**Comment by roedesh** [comment]
There should be a badge like this at the top of the README:

<a href="https://chrome.google.com/webstore/detail/copy-guard/kobgknfkonpcnijbmjpepfonpnkeefij"><img alt="Chrome Web Store" src="https://img.shields.io/chrome-web-store/v/kobgknfkonpcnijbmjpepfonpnkeefij"></a>

**Comment by kaushalyap** [comment]
Thanks did not noticed it, consider adding a link to repo description so it is obvious.

**Comment by roedesh** [comment]
I have added the badges to the About section as well. The repo description does not allow links unfortunately.

**Comment by kaushalyap** [comment]
> I have added the badges to the About section as well.

Okay thanks that is good!
